### ISSUE TITLE
Fix 404 errors on course page

### ISSUE THREAD

**Issue by plahteenlahti** [intelligenzia/Salainen-Tiedekunta#7]
Currently, if you navigate to a course page for example from the index page and then refresh the course the page will give 404 error. This is most likely caused by incorrect next.js configuration.

**Comment by thesanjeevsharma** [comment]
Hello, I would like to work on this.

**Comment by plahteenlahti** [comment]
@thesanjeevsharma cool! I think it has something to do with next.js routes being configured wrong.
